require('plugins')
require('options')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('autopairs-config')
require('nvim-tree-config')
require('keybindings')
require('whichkey-config')
require('telescope-config')
require('lsp')
require('colorizer-config')
require('toggleterm-config')
require('comment-config')
require('dashboard-config')
vim.cmd('colorscheme nord')
